server:
  port: 7180

eureka:
  instance:
    appname: truck-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
management:
  security:
    enabled: false